[build]
builder = "NIXPACKS"
buildCommand = "NITRO_PRESET=node-server npx vite build && npm run db:migrate"

[deploy]
startCommand = "node .output/server/index.mjs"
healthcheckPath = "/api/v1"
restartPolicyType = "ON_FAILURE"
