/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as WorkRouteImport } from './routes/work'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkMeRouteImport } from './routes/work.me'
import { Route as WorkStallRouteImport } from './routes/work.stall'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkMeRoute = WorkMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => WorkRoute,
} as any)
const WorkStallRoute = WorkStallRouteImport.update({
  id: '/stall',
  path: '/stall',
  getParentRoute: () => WorkRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/work': typeof WorkRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/work/me': typeof WorkMeRoute
  '/work/stall': typeof WorkStallRoute
  '/work/': typeof WorkIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/p/$id': typeof PIdRoute
  '/work/me': typeof WorkMeRoute
  '/work/stall': typeof WorkStallRoute
  '/work': typeof WorkIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/work': typeof WorkRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/work/me': typeof WorkMeRoute
  '/work/stall': typeof WorkStallRoute
  '/work/': typeof WorkIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/inbox'
    | '/login'
    | '/me'
    | '/work'
    | '/p/$id'
    | '/work/me'
    | '/work/stall'
    | '/work/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/inbox'
    | '/login'
    | '/me'
    | '/p/$id'
    | '/work/me'
    | '/work/stall'
    | '/work'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/inbox'
    | '/login'
    | '/me'
    | '/work'
    | '/p/$id'
    | '/work/me'
    | '/work/stall'
    | '/work/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  WorkRoute: typeof WorkRouteWithChildren
  PIdRoute: typeof PIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/me': {
      id: '/work/me'
      path: '/me'
      fullPath: '/work/me'
      preLoaderRoute: typeof WorkMeRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/stall': {
      id: '/work/stall'
      path: '/stall'
      fullPath: '/work/stall'
      preLoaderRoute: typeof WorkStallRouteImport
      parentRoute: typeof WorkRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkRouteChildren {
  WorkMeRoute: typeof WorkMeRoute
  WorkStallRoute: typeof WorkStallRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkMeRoute: WorkMeRoute,
  WorkStallRoute: WorkStallRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  WorkRoute: WorkRouteWithChildren,
  PIdRoute: PIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
