/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MailRouteImport } from './routes/mail'
import { Route as MeRouteImport } from './routes/me'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPushRouteImport } from './routes/admin.push'
import { Route as AdminStallsRouteImport } from './routes/admin.stalls'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiV1RouteImport } from './routes/api/v1'
import { Route as MailIndexRouteImport } from './routes/mail.index'
import { Route as MailIdRouteImport } from './routes/mail.$id'
import { Route as OwnedIdRouteImport } from './routes/owned.$id'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkFeedRouteImport } from './routes/work.feed'
import { Route as WorkMailRouteImport } from './routes/work.mail'
import { Route as WorkMeRouteImport } from './routes/work.me'
import { Route as WorkStallRouteImport } from './routes/work.stall'
import { Route as WorkStatsRouteImport } from './routes/work.stats'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMailSplatRouteImport } from './routes/api/mail/$'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as WorkMailIndexRouteImport } from './routes/work.mail.index'
import { Route as WorkMailIdRouteImport } from './routes/work.mail.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPushRoute = AdminPushRouteImport.update({
  id: '/push',
  path: '/push',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStallsRoute = AdminStallsRouteImport.update({
  id: '/stalls',
  path: '/stalls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const MailIndexRoute = MailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MailRoute,
} as any)
const MailIdRoute = MailIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MailRoute,
} as any)
const OwnedIdRoute = OwnedIdRouteImport.update({
  id: '/owned/$id',
  path: '/owned/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkFeedRoute = WorkFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => WorkRoute,
} as any)
const WorkMailRoute = WorkMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => WorkRoute,
} as any)
const WorkMeRoute = WorkMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => WorkRoute,
} as any)
const WorkStallRoute = WorkStallRouteImport.update({
  id: '/stall',
  path: '/stall',
  getParentRoute: () => WorkRoute,
} as any)
const WorkStatsRoute = WorkStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => WorkRoute,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailSplatRoute = ApiMailSplatRouteImport.update({
  id: '/api/mail/$',
  path: '/api/mail/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiV1Route,
} as any)
const WorkMailIndexRoute = WorkMailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkMailRoute,
} as any)
const WorkMailIdRoute = WorkMailIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkMailRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRouteWithChildren
  '/desk': typeof DeskRoute
  '/feed': typeof FeedRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRouteWithChildren
  '/me': typeof MeRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/push': typeof AdminPushRoute
  '/admin/stalls': typeof AdminStallsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/mail/$id': typeof MailIdRoute
  '/owned/$id': typeof OwnedIdRoute
  '/p/$id': typeof PIdRoute
  '/work/feed': typeof WorkFeedRoute
  '/work/mail': typeof WorkMailRouteWithChildren
  '/work/me': typeof WorkMeRoute
  '/work/stall': typeof WorkStallRoute
  '/work/stats': typeof WorkStatsRoute
  '/admin/': typeof AdminIndexRoute
  '/mail/': typeof MailIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mail/$': typeof ApiMailSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/work/mail/$id': typeof WorkMailIdRoute
  '/work/mail/': typeof WorkMailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/desk': typeof DeskRoute
  '/feed': typeof FeedRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/push': typeof AdminPushRoute
  '/admin/stalls': typeof AdminStallsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/mail/$id': typeof MailIdRoute
  '/owned/$id': typeof OwnedIdRoute
  '/p/$id': typeof PIdRoute
  '/work/feed': typeof WorkFeedRoute
  '/work/me': typeof WorkMeRoute
  '/work/stall': typeof WorkStallRoute
  '/work/stats': typeof WorkStatsRoute
  '/admin': typeof AdminIndexRoute
  '/mail': typeof MailIndexRoute
  '/work': typeof WorkIndexRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mail/$': typeof ApiMailSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/work/mail/$id': typeof WorkMailIdRoute
  '/work/mail': typeof WorkMailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRouteWithChildren
  '/desk': typeof DeskRoute
  '/feed': typeof FeedRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRouteWithChildren
  '/me': typeof MeRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/push': typeof AdminPushRoute
  '/admin/stalls': typeof AdminStallsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/mail/$id': typeof MailIdRoute
  '/owned/$id': typeof OwnedIdRoute
  '/p/$id': typeof PIdRoute
  '/work/feed': typeof WorkFeedRoute
  '/work/mail': typeof WorkMailRouteWithChildren
  '/work/me': typeof WorkMeRoute
  '/work/stall': typeof WorkStallRoute
  '/work/stats': typeof WorkStatsRoute
  '/admin/': typeof AdminIndexRoute
  '/mail/': typeof MailIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mail/$': typeof ApiMailSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/work/mail/$id': typeof WorkMailIdRoute
  '/work/mail/': typeof WorkMailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/admin'
    | '/desk'
    | '/feed'
    | '/inbox'
    | '/login'
    | '/mail'
    | '/me'
    | '/work'
    | '/admin/orders'
    | '/admin/push'
    | '/admin/stalls'
    | '/admin/users'
    | '/api/v1'
    | '/mail/$id'
    | '/owned/$id'
    | '/p/$id'
    | '/work/feed'
    | '/work/mail'
    | '/work/me'
    | '/work/stall'
    | '/work/stats'
    | '/admin/'
    | '/mail/'
    | '/work/'
    | '/api/admin/session'
    | '/api/auth/$'
    | '/api/mail/$'
    | '/api/media/$'
    | '/api/v1/$'
    | '/work/mail/$id'
    | '/work/mail/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/desk'
    | '/feed'
    | '/inbox'
    | '/login'
    | '/me'
    | '/admin/orders'
    | '/admin/push'
    | '/admin/stalls'
    | '/admin/users'
    | '/api/v1'
    | '/mail/$id'
    | '/owned/$id'
    | '/p/$id'
    | '/work/feed'
    | '/work/me'
    | '/work/stall'
    | '/work/stats'
    | '/admin'
    | '/mail'
    | '/work'
    | '/api/admin/session'
    | '/api/auth/$'
    | '/api/mail/$'
    | '/api/media/$'
    | '/api/v1/$'
    | '/work/mail/$id'
    | '/work/mail'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/admin'
    | '/desk'
    | '/feed'
    | '/inbox'
    | '/login'
    | '/mail'
    | '/me'
    | '/work'
    | '/admin/orders'
    | '/admin/push'
    | '/admin/stalls'
    | '/admin/users'
    | '/api/v1'
    | '/mail/$id'
    | '/owned/$id'
    | '/p/$id'
    | '/work/feed'
    | '/work/mail'
    | '/work/me'
    | '/work/stall'
    | '/work/stats'
    | '/admin/'
    | '/mail/'
    | '/work/'
    | '/api/admin/session'
    | '/api/auth/$'
    | '/api/mail/$'
    | '/api/media/$'
    | '/api/v1/$'
    | '/work/mail/$id'
    | '/work/mail/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AdminRoute: typeof AdminRouteWithChildren
  DeskRoute: typeof DeskRoute
  FeedRoute: typeof FeedRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MailRoute: typeof MailRouteWithChildren
  MeRoute: typeof MeRoute
  WorkRoute: typeof WorkRouteWithChildren
  ApiV1Route: typeof ApiV1RouteWithChildren
  OwnedIdRoute: typeof OwnedIdRoute
  PIdRoute: typeof PIdRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMailSplatRoute: typeof ApiMailSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/push': {
      id: '/admin/push'
      path: '/push'
      fullPath: '/admin/push'
      preLoaderRoute: typeof AdminPushRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stalls': {
      id: '/admin/stalls'
      path: '/stalls'
      fullPath: '/admin/stalls'
      preLoaderRoute: typeof AdminStallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/': {
      id: '/mail/'
      path: '/'
      fullPath: '/mail/'
      preLoaderRoute: typeof MailIndexRouteImport
      parentRoute: typeof MailRoute
    }
    '/mail/$id': {
      id: '/mail/$id'
      path: '/$id'
      fullPath: '/mail/$id'
      preLoaderRoute: typeof MailIdRouteImport
      parentRoute: typeof MailRoute
    }
    '/owned/$id': {
      id: '/owned/$id'
      path: '/owned/$id'
      fullPath: '/owned/$id'
      preLoaderRoute: typeof OwnedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/feed': {
      id: '/work/feed'
      path: '/feed'
      fullPath: '/work/feed'
      preLoaderRoute: typeof WorkFeedRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/mail': {
      id: '/work/mail'
      path: '/mail'
      fullPath: '/work/mail'
      preLoaderRoute: typeof WorkMailRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/me': {
      id: '/work/me'
      path: '/me'
      fullPath: '/work/me'
      preLoaderRoute: typeof WorkMeRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/stall': {
      id: '/work/stall'
      path: '/stall'
      fullPath: '/work/stall'
      preLoaderRoute: typeof WorkStallRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/stats': {
      id: '/work/stats'
      path: '/stats'
      fullPath: '/work/stats'
      preLoaderRoute: typeof WorkStatsRouteImport
      parentRoute: typeof WorkRoute
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/$': {
      id: '/api/mail/$'
      path: '/api/mail/$'
      fullPath: '/api/mail/$'
      preLoaderRoute: typeof ApiMailSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof ApiV1Route
    }
    '/work/mail/': {
      id: '/work/mail/'
      path: '/'
      fullPath: '/work/mail/'
      preLoaderRoute: typeof WorkMailIndexRouteImport
      parentRoute: typeof WorkMailRoute
    }
    '/work/mail/$id': {
      id: '/work/mail/$id'
      path: '/$id'
      fullPath: '/work/mail/$id'
      preLoaderRoute: typeof WorkMailIdRouteImport
      parentRoute: typeof WorkMailRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPushRoute: typeof AdminPushRoute
  AdminStallsRoute: typeof AdminStallsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPushRoute: AdminPushRoute,
  AdminStallsRoute: AdminStallsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MailRouteChildren {
  MailIdRoute: typeof MailIdRoute
  MailIndexRoute: typeof MailIndexRoute
}

const MailRouteChildren: MailRouteChildren = {
  MailIdRoute: MailIdRoute,
  MailIndexRoute: MailIndexRoute,
}

const MailRouteWithChildren = MailRoute._addFileChildren(MailRouteChildren)

interface WorkMailRouteChildren {
  WorkMailIdRoute: typeof WorkMailIdRoute
  WorkMailIndexRoute: typeof WorkMailIndexRoute
}

const WorkMailRouteChildren: WorkMailRouteChildren = {
  WorkMailIdRoute: WorkMailIdRoute,
  WorkMailIndexRoute: WorkMailIndexRoute,
}

const WorkMailRouteWithChildren = WorkMailRoute._addFileChildren(
  WorkMailRouteChildren,
)

interface WorkRouteChildren {
  WorkFeedRoute: typeof WorkFeedRoute
  WorkMailRoute: typeof WorkMailRouteWithChildren
  WorkMeRoute: typeof WorkMeRoute
  WorkStallRoute: typeof WorkStallRoute
  WorkStatsRoute: typeof WorkStatsRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkFeedRoute: WorkFeedRoute,
  WorkMailRoute: WorkMailRouteWithChildren,
  WorkMeRoute: WorkMeRoute,
  WorkStallRoute: WorkStallRoute,
  WorkStatsRoute: WorkStatsRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

interface ApiV1RouteChildren {
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

const ApiV1RouteChildren: ApiV1RouteChildren = {
  ApiV1SplatRoute: ApiV1SplatRoute,
}

const ApiV1RouteWithChildren = ApiV1Route._addFileChildren(ApiV1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AdminRoute: AdminRouteWithChildren,
  DeskRoute: DeskRoute,
  FeedRoute: FeedRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MailRoute: MailRouteWithChildren,
  MeRoute: MeRoute,
  WorkRoute: WorkRouteWithChildren,
  ApiV1Route: ApiV1RouteWithChildren,
  OwnedIdRoute: OwnedIdRoute,
  PIdRoute: PIdRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMailSplatRoute: ApiMailSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
